version: '3.6'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - proj
    volumes:
      - my-db:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: proj7-backend:${VERSION}
    container_name: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB: ${DB}
      DB_USER: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 9001:9001
    depends_on:
      - db
    networks:
      - proj
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: proj7-frontend:${VERSION}
    container_name: frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
      - backend
    networks:
      - proj
networks:
  proj:
    external:
      name: proj
volumes:
  my-db:
