version : "3.6"
services:
  jenkins:    
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always    
    ports:
      - 8080:8080
    restart: always   
    volumes:
      - /home/zymr/devops-proj-7-develop/jenkins-volume:/var/jenkins_home
